# name: Trigger GitLab Pipeline

# on:
#   push:
#     branches:
#       - main  # Adjust as needed

# jobs:
#   trigger-gitlab:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger GitLab Pipeline
#         run: |
#           curl -X POST "https://gitlab.com/api/v4/projects/68405524/trigger/pipeline" \
            # --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
#             --form "ref=main"

# name: Trigger GitLab CI/CD

# on:
#   push:
#     branches:
#       - main  # Or any branch you want

# jobs:
#   trigger-gitlab-ci:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Capture Commit ID
#         id: commit
#         run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

#       - name: Trigger GitLab Pipeline
#         run: |
#           curl --request POST "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline" \
#           --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
#           --form "ref=main" \
#           --form "variables[COMMIT_ID]=${{ env.commit_id }}"

name: Trigger GitLab CI/CD

on:
  push:
    branches:
      - main  # Or any branch you want

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Capture Commit ID
        id: commit
        run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline" \
          --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
          --form "ref=main" \
          --form "variables[COMMIT_ID]=${{ env.commit_id }}"